### ISSUE TITLE
Incorrect default for inner looping variable

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#28] opened 2018-08-29 19:09 UTC
There's an issue with what the default is for looping variables in foreach loops, but only in nested loops and under certain scenarios.

In the following class
```java
public class NestedLoops {
  public static @PolyDet int @PolyDet [] makeArr(@PolyDet int n) {
    return new @PolyDet int @PolyDet [] { n };
  }

  public static void f(@Det int n) {
    for (int i : makeArr(n)) {
      for (int j : makeArr(i)) {
        @Det int m = j;
      }
    }
  }

  public static void f2(@Det int n) {
    for (int i : makeArr(n)) {
      for (@Det int j : makeArr(i)) {
        @Det int m = j;
      }
    }
  }
}
```
we get the error
```
NestedLoops.java:11: error: [assignment.type.incompatible] incompatible types in assignment.
        @Det int m = j;
                     ^
  found   : @NonDet int
  required: @Det int
```

This is odd for several reasons. First, there is no error in `f2` where the inner looping variable is `@Det`, so no type rules are being broken, it's simply that the default here is `@NonDet` when it should be `@Det`. Secondly, this only happens with the inner loop, not the outer loop. Finally, I thought the issue might be with how `@PolyDet` is resolved for variables that were type refined to `@Det`. This isn't the case though, as changing all instances of `@Det` to `@PolyDet` in the above example still gives the same error. Also, when I try a similar piece of code in sequence without foreach loops, there's no error. This means the error is with the foreach loop itself.

**Comment by t-rasmud** [comment] 2018-09-26 22:35
Checker framework bug - https://github.com/typetools/checker-framework/issues/2172

**Comment by mernst** [comment] 2018-11-02 20:59
Duplicate of typetools#2172

**Closed by mernst** 2018-11-02 20:59 UTC
